# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "2"

networks:
    test:

services:
    pub_ca_org1:
        image: hyperledger/fabric-ca:$IMAGE_TAG
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-org1
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_PORT=7154
        ports:
            - "7154:7154"
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        volumes:
            - ../organizations/fabric-ca/org1:/etc/hyperledger/fabric-ca-server
        container_name: pub_ca_org1
        networks:
            - test

    pub_ca_org2:
        image: hyperledger/fabric-ca:$IMAGE_TAG
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-org2
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_PORT=8154
        ports:
            - "8154:8154"
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        volumes:
            - ../organizations/fabric-ca/org2:/etc/hyperledger/fabric-ca-server
        container_name: pub_ca_org2
        networks:
            - test

    pub_ca_orderer:
        image: hyperledger/fabric-ca:$IMAGE_TAG
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-orderer
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_PORT=9154
        ports:
            - "9154:9154"
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        volumes:
            - ../organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
        container_name: pub_ca_orderer
        networks:
            - test
